[package]
name = "nr2"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
nostr = "0.43"
nostr-sdk = "0.43"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9.7"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1"
